### ISSUE TITLE
[PE-D][Tester E] Missing Sex

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-T10-2/tp#312]
Input: add n/James Ho ic/S9534567A p/91234567 d/Asthma m/Albuterol ha/NUS-PGPR dob/01011995 v/21-10-2024 15:48
al/Pollen s/Female mh/Diabetes

Output: Does not have sex displayed when using list
![image.png](https://raw.githubusercontent.com/shaunngoh/ped/main/files/ba1f9360-f7da-489d-bdb1-77e790ef5ba4.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: shaunngoh/ped#6

**Comment by yentheng0110** [comment]
![image](https://github.com/user-attachments/assets/bfaa681c-a883-4471-8e30-b5d517aa4ab4)
![image](https://github.com/user-attachments/assets/45233f5f-eec9-402b-aac0-df35861424cf)
There is no issue with missing sex, the output shown by the tester has missing allergy, sex and medical history, which I suspect it's because al/Pollen s/Female mh/Diabetes is written on another line from the rest of the input.
